pekko {

  loggers = ["org.apache.pekko.event.slf4j.Slf4jLogger"]
  loglevel = "INFO"
  logging-filter = "org.apache.pekko.event.slf4j.Slf4jLoggingFilter"
  
  actor {

    debug {
      lifecycle = on
      log-sent-messages = on
    }

    provider = cluster

    serializers {
       kryo = "io.altoo.serialization.kryo.pekko.PekkoKryoSerializer"
    }

    serialization-bindings {
      "core.ActorProtocol" = kryo
    }

  }
  
  remote {
    artery {
      enabled = on
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 7355
      # advanced.maximum-frame-size = 1048576
    }
  }

# You should not add more members to the cluster than quorum-size * 2 - 1
  cluster {
    seed-nodes = [
      "pekko://application@127.0.0.1:7354",
      "pekko://application@127.0.0.1:7355"
     ]

   downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
     
    split-brain-resolver {
      active-strategy = static-quorum #  Generally the quorum-size is always greater than 1/2 of the number of nodes in the cluster
       
      static-quorum {
      # minimum number of nodes that the cluster must have
      quorum-size = 2  # in production we must have 12 nodes / 2 
      }
    }
   
  }
}

pekko-kryo-serialization {
  type = "graph"
  id-strategy = "default"
  post-serialization-transformations = "lz4"
  implicit-registration-logging = true
  # If enabled, Kryo logs a lot of information about serialization process.
  # Useful for debugging and low-level tweaking
  kryo-trace = false

}

pekko.extensions = ["org.apache.pekko.cluster.pubsub.DistributedPubSub"]

pekko.cluster.log-info-verbose = on


pekko.actor.warn-about-java-serializer-usage = on
pekko.actor.allow-java-serialization = off

