version: '2'
services:

  prometheus:
      image: prom/prometheus:v2.17.1
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./:/etc/prometheus/
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      expose:
        - 9090
      ports:
        - 9090:9090
    
  grafana:
      image: grafana/grafana:6.7.2
      container_name: grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      expose:
        - 3000
      ports:
        - 3000:3000
